[package]
name = "opcua-proxy"
description = "OPC-UA proxy"
version = "4.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap-verbosity-flag = "2.0.0"
futures-util = "0.3.27"
mongodb = "2.4.0"
serde = { version = "1.0.156", features = [ "derive" ] }
serde_json = "1.0.94"
signal-hook = { version = "0.3.15", default-features = false }
signal-hook-tokio = { version = "0.3.1", features = [ "futures-v0_3" ] }
tokio = { version = "1.26.0", features = [ "macros", "rt", "sync" ] }
tracing = "0.1.37"

[dependencies.clap]
version = "4.1.9"
default-features = false
features = [ "std", "help", "usage", "error-context", "derive", "env" ]

[dependencies.opcua]
version = "0.11.0"
default-features = false
features = [ "client", "vendored-openssl" ]

[dependencies.tracing-log]
version = "0.1.3"
default-features = false
features = [ "std", "log-tracer" ]

[dependencies.tracing-subscriber]
version = "0.3.16"
default-features = false
features = [ "smallvec", "fmt", "ansi" ]

[dev-dependencies]
serde_test = "1.0.157"
