[package]
name = "opcua-proxy"
description = "OPC-UA proxy"
version = "4.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
awc = { version = "3.1.1", default-features = false }
clap-verbosity-flag = "2.0.1"
env_logger = { version = "0.10.0", default-features = false }
futures-util = "0.3.28"
mongodb = "2.5.0"
serde = { version = "1.0.162", features = [ "derive" ] }
signal-hook = { version = "0.3.15", default-features = false }
signal-hook-tokio = { version = "0.3.1", features = [ "futures-v0_3" ] }
tracing = "0.1.37"
url = "2.3.1"

[dependencies.clap]
version = "4.2.7"
default-features = false
features = [ "std", "help", "usage", "error-context", "derive", "env" ]

[dependencies.opcua]
version = "0.11.0"
default-features = false
features = [ "client", "vendored-openssl" ]

[dependencies.tokio]
version = "1.28.0"
features = [ "macros", "rt-multi-thread", "sync" ]

[dependencies.tracing-log]
version = "0.1.3"
default-features = false
features = [ "std" ]

[dependencies.tracing-subscriber]
version = "0.3.17"
default-features = false
features = [ "ansi", "fmt", "parking_lot", "smallvec", "std" ]

[dev-dependencies]
serde_test = "1.0.162"
