[package]
name = "opcua-proxy"
description = "OPC-UA proxy"
version = "6.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
arcstr = "1.1.5"
clap-verbosity-flag = "2.0.1"
env_logger = { version = "0.10.0", default-features = false }
futures-util = "0.3.30"
mongodb = "2.7.0"
serde = { version = "1.0.198", features = [ "derive" ] }
signal-hook = { version = "0.3.17", default-features = false }
signal-hook-tokio = { version = "0.3.1", features = [ "futures-v0_3" ] }
tokio-util = "0.7.10"
tracing = "0.1.40"
url = "2.4.1"

[dependencies.clap]
version = "4.5.4"
default-features = false
features = [ "std", "help", "usage", "error-context", "derive", "env" ]

[dependencies.opcua]
version = "0.12.0"
default-features = false
features = [ "client", "vendored-openssl" ]

[dependencies.reqwest]
version = "0.11.22"
default-features = false
features = [ "json" ]

[dependencies.tokio]
version = "1.37.0"
features = [ "macros", "rt-multi-thread", "sync" ]

[dependencies.tracing-log]
version = "0.1.3"
default-features = false
features = [ "std" ]

[dependencies.tracing-subscriber]
version = "0.3.17"
default-features = false
features = [ "ansi", "fmt", "parking_lot", "smallvec", "std" ]
