[package]
name = "opcua-proxy"
description = "OPC-UA proxy"
version = "3.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
anyhow = "1.0.66"
clap-verbosity-flag = "2.0.0"
futures-util = "0.3.25"
mongodb = "2.3.1"
serde = { version = "1.0.147", features = [ "derive" ] }
serde_json = "1.0.88"
tokio = { version = "1.22.0", features = [ "macros" ] }
tracing = "0.1.37"

[dependencies.opcua]
version = "0.11.0"
default-features = false
features = [ "client" ]

[dependencies.clap]
version = "4.0.26"
default-features = false
features = [ "std", "help", "usage", "error-context", "derive", "env" ]

[dependencies.signal-hook]
version = "0.3.14"
default-features = false
features = [ "iterator" ]

[dependencies.tracing-log]
version = "0.1.3"
default-features = false
features = [ "std", "log-tracer" ]

[dependencies.tracing-subscriber]
version = "0.3.16"
default-features = false
features = [ "smallvec", "fmt", "ansi" ]

[dev-dependencies]
serde_test = "1.0.147"
